[IO]
  wr_integrals_freq = -1
  plot_var_1 = "dust"
  plot_var_2 = "velx"
  plot_var_3 = "vely"
  plot_var_4 = "dfun" 
  ignoreForcedPlot = true

[Grid]
  xmin = 0.0
  xmax = 1.0
  ymin = 0.0
  ymax = 1.0
  xl_boundary_type = "noslip_ins"
  xr_boundary_type = "noslip_ins"
  yl_boundary_type = "noslip_ins"
  yr_boundary_type = "noslip_ins"
  nblockx = 4
  nblocky = 4

[IncompNS]
  ins_cflFlg = 0
  ins_cfl = 1.0
  ins_sigma = 1.0
  ins_dtSpec = 1.0e-5

[Driver]
  dtinit = 1.0e-5
  tstep_change_factor = 1.0
