[Driver]
  restart = false
  nend = 50000
  tmax = 0.15

[IO] 
  checkpointFileNumber = 0
  plotFileNumber = 0

[Grid]
  amrexFaceInterpolator = "face_div_free"
  nrefs = 2
  lrefine_min = 1
  lrefine_max = 5
  refine_var_count = 1
  refine_var_1 = "dfun"
  refine_cutoff_1 = 0.0
  derefine_cutoff_1 = -0.01
